#!/bin/bash
set -e

# COLORS
BLUE='\033[1;36m'
GREEN='\033[0;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'

# NO COLOR / ORIGINAL COLOR
NC='\033[0m'

echo -e "ADDING FISH REPO\n\n"
apt-add-repository ppa:fish-shell/release-3 -y
echo -e "\n\nFISH REPO ${GREEN}ADDED$NC\n\n"

echo -e "UPDATING APT\n\n"
apt-get update
echo -e "\n\nAPT ${GREEN}UPDATED$NC\n\n"

echo -e "INSTALLING ${YELLOW}FISH$NC\n\n"
apt-get install fish -y
echo -e "\n\n${YELLOW}FISH$NC READY TO ${BLUE}SWIM$NC\n\n"

echo -e "INSTALLING ${BLUE}OMF$NC\n\n"
curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install > install
chmod +x install
./install --noninteractive
fish -c './knock-down'
